AWSTemplateFormatVersion: 2010-09-09
Description: Template to create an SCP that denies access to S3

Resources:
  ScpDenyS3:
    Type: AWS::Organizations::Policy
    Properties:
      Content: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Deny",
              "Action": "s3:*",
              "Resource": "*"
            }
          ]
        }
      Description: "SCP to deny access to S3"
      Name: "ScpDenyS3"
      Type: SERVICE_CONTROL_POLICY